name: Testing retrapi docker build

on:
  push: # trigger only on main branch
    branches:
      - main
    # trigger only on changes to the following files
    paths:
      - "api/retrapi/src/**"
      - "api/retrapi/environment.yml"
      - "api/retrapi/requirements.txt"
      - "api/retrapi/poetry.lock"
      - "api/retrapi/pyproject.toml"
      - "api/retrapi/Dockerfile"
      - ".github/workflows/test-retrapi-docker.yml"
  pull_request: # trigger only on main branch
    branches:
      - main
    # trigger only on changes to the following files
    paths:
      - "api/retrapi/src/**"
      - "api/retrapi/environment.yml"
      - "api/retrapi/requirements.txt"
      - "api/retrapi/poetry.lock"
      - "api/retrapi/pyproject.toml"
      - "api/retrapi/Dockerfile"
      - ".github/workflows/test-retrapi-docker.yml"

jobs:
  docker-build:
    runs-on: ubuntu-20.04
    steps:
      - # get repository code
        name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build the image
        uses: docker/build-push-action@v2
        with:
          context: api/retrapi
          push: false
          tags: retrapi:latest
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, mode=max, scope=${{ github.workflow }}
